[
  ['Test = read File.',
   's(:activity, s(:variable, Test), s(:action, read), s(:subject, File))'],
  ['read with something.',
   's(:activity, s(:action, read), s(:condition, something))'],
  ['read.',
   's(:activity, s(:action, read))'],
  ['Test = read File with something.',
   's(:activity, s(:variable, Test), s(:action, read), s(:subject, File), s(:condition, something))'],
  ['read File /tmp/test.txt.',
   's(:activity, s(:action, read), s(:subject, File, s(:subject_arguments, "/tmp/test.txt")))'],
  ['with something.',
   's(:activity, s(:action, with, s(:action_arguments, "something")))'],
  ['Test = read very http://example.com slowly File file:///tmp/test.txt with something.',
   's(:activity, s(:variable, Test), s(:action, read, s(:action_arguments, "very http://example.com slowly")), s(:subject, File, s(:subject_arguments, "file:///tmp/test.txt")), s(:condition, something))'],
  ['read very slowly.',
   's(:activity, s(:action, read, s(:action_arguments, "very slowly")))'],
  ['read very slowly with something.',
   's(:activity, s(:action, read, s(:action_arguments, "very slowly")), s(:condition, something))'],
  ['read very slowly with something else like this ftp://test.txt.',
   's(:activity, s(:action, read, s(:action_arguments, "very slowly")), s(:condition, something, c(:condition_arguments, "else like this ftp://test.txt")))'],
  ['Test = read File1 and File2 with something.',
   's(:activity, s(:variable, Test), s(:action, read), s(:subject, File1), s(:subject, File2), s(:condition, something))'],

  ['Test = read File1 and File2[] and File3.',
   's(:activity, s(:variable, Test), s(:action, read), s(:subject, File1), s(:list_variable, File2[]), s(:subject, File3))'],

  ['Test = read File1 /tmp/test.txt and File2 with something.',
   's(:activity, s(:variable, Test), s(:action, read), s(:subject, File1, s(:subject_arguments, "/tmp/test.txt")), s(:subject, File2), s(:condition, something))'],
  ['Test = read File1 /tmp/test.txt and File2 /tmp/test.aaa.',
   's(:activity, s(:variable, Test), s(:action, read), s(:subject, File1, s(:subject_arguments, "/tmp/test.txt")), s(:subject, File2, s(:subject_arguments, "/tmp/test.aaa")))'],
  ['T[] = read.',
   's(:activity, s(:list_variable, T[]), s(:action, read))'],
  ['read T[].',
   's(:activity, s(:action, read), s(:list_variable, T[]))']]
